### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by mgencur**
The nightly job started to fail because the underlying dependencies have moved forward. Sync with upstream to get latest code.

### CODE REVIEW

**Comment by mgencur** [comment]
Hmm. So the latest commit fixed it. But it means that the "latest" version of eventing sources is probably broken (https://knative-releases.storage.googleapis.com/eventing-sources/latest/release.yaml). All other dependencies are at "latest" as well. I'm wondering how the tests can work upstream.

**Comment by bbrowning** [comment]
Upstream Knative has already moved on to 0.3 release branch so even though their 0.2 branch points to latest, the chances of a build running on that branch again are slim.

With that said, this did uncover that even HEAD of the master branch upstream is pointing to an old eventing-sources from early December. That's unintended I'm sure.

**Comment by bbrowning** [comment]
@mgencur That's fine. Just as a note, upstream Knative Eventing has removed its dependency on eventing-sources for its e2e tests. So when we next sync our master with upstream we can do the same.

**Pull request merged**
