### PR TITLE
Install yq in the build image for CI

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

/assign @mgencur

### CODE REVIEW

**Comment by mgencur** [comment]
Are you using this tool in the knative-eventing repo? Otherwise it's not required. Just want to know the reason for this PR.

**Comment by matzew** [comment]
yeah, @mgencur we run `hack/install`  and I want to migrate to 1.10+ soon-ish

**Pull request merged**
