### PR TITLE
Invert loop

### PR DESCRIPTION
**Pull request by mgencur**
If this passes then it will replace the other PR from Markus.

### CODE REVIEW

**Comment by mgencur** [comment]
/retest
After syncing with v0.2.1...

**Comment by alanfx** [comment]
So `prow` isn't dead!
/retest

**Comment by mgencur** [comment]
@alanfx the tests are passing now

**Comment by alanfx** [comment]
Thanks a lot, Martin. I'll have to remember the close and reopen trick!
/lgtm

**Pull request merged**
