### PR TITLE
[0.17] Backport https://github.com/knative/pkg/pull/1842

### PR DESCRIPTION
**Pull request by aliok**
Backport https://github.com/knative/pkg/pull/1842

### CODE REVIEW

**Comment by lberk** [comment]
did this backport not need to update the dep in `go.mod` or `go.sum` ?

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
> did this backport not need to update the dep in go.mod or go.sum ?

I believe it does not work, since upstream was fixed for 0.18. so the idea was just patching the vendor'ed sources

**Comment by lberk** [comment]
@matzew the linked pkg pr is against the 0.17 of pkg -- why aren't we using gomod to track those dependencies for the correct branch?

**Comment by matzew** [comment]
Or should we port the upstream fix and remove this on the actual 0.17 branch, for pkg?

https://github.com/knative/pkg/blob/release-0.17/webhook/resourcesemantics/conversion/conversion.go#L133

I guess that way we could/would be able to vendor the "right" release sha, pointing to pkg 0.17.x

**Comment by matzew** [comment]
> why aren't we using gomod to track those dependencies for the correct branch?

Ah! good! I did not see the PR for the pkg 0.17 

Totally agree. lets get that in to pkg and _than_ use the go mod way to update this!  Thanks for catching!

/hold

**Comment by aliok** [comment]
@lberk 
Good point. I got the impression that it wasn't working and I need to patch stuff manually.

But, let's get https://github.com/knative/pkg/pull/1842 merged and then I can play with gomod

**Comment by aliok** [comment]
@lberk @matzew 
https://github.com/knative/pkg/pull/1842 is merged and `go get -u knative.dev/pkg@release-0.17` did the trick.

Compared to https://github.com/openshift/knative-eventing-contrib/pull/610 though, `go get` upgraded a few more things. I don't expect any problems though.

**Comment by lberk** [comment]
thanks @aliok !

/lgtm
/approve

**Pull request merged**
