### PR TITLE
Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by matzew** [comment]
@alanfx  the fix for:  https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_knative-eventing/88/pull-ci-openshift-knative-eventing-release-next-images/6  


is what I need to tweak here - files have been a) renamed and b) moved :-) 

glad this job does what it's supposed to be

**Comment by alanfx** [comment]
OK, I'm closing this, so the Jenkins job can run later...

**Pull request closed without merging**
