### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by aliok** [comment]
/retest

```
Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
```

**Comment by aliok** [comment]
/retest

```
mp/openshift-install-194801972/route53/base.tf line 42, in resource "aws_route53_record" "api_external_alias":
```

**Comment by aliok** [comment]
@matzew FYI, I am working on this here: https://github.com/openshift/knative-eventing/pull/1319

I couldn't figure out why that error happens. Now, I am trying to revert commits until it doesn't fail to identify the offending change. That takes time though, because tests take long and there are infra problems

**Comment by matzew** [comment]
/close 

closing all for new state of test

**Pull request closed without merging**
