### PR TITLE
See if we can run the rek tests here too

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

/hold

this is test

### CODE REVIEW

**Comment by matzew** [comment]
```
INFO[2021-04-22T11:48:06Z] error attempting to ko publish: exec: "ko": executable file not found in $PATH 
INFO[2021-04-22T11:48:06Z] --- FAIL: TestBrokerWithDLQ (0.00s)          
INFO[2021-04-22T11:48:06Z] panic: exec: "ko": executable file not found in $PATH [recovered] 
INFO[2021-04-22T11:48:06Z] 	panic: exec: "ko": executable file not found in $PATH 
INFO[2021-04-22T11:48:06Z]                                              
```

some image build things to do first :smile:

**Comment by mgencur** [comment]
FYI, it's not possible to run `ko` in an image in OpenShift CI. If you need to build an image they need to be built by ci-operator, not via `ko`

**Comment by matzew** [comment]
> FYI, it's not possible to run ko in an image in OpenShift CI. If you need to build an image they need to be built by ci-operator, not via ko

I know, that's why I wrote `some image build things to do first` :wink:

**Comment by mgencur** [comment]
OK. I thought you just wanted to include `ko` in the image.

**Comment by matzew** [comment]
@lionelvillard on this:

```
INFO[2021-04-22T11:48:06Z] error attempting to ko publish: exec: "ko": executable file not found in $PATH 
INFO[2021-04-22T11:48:06Z] --- FAIL: TestBrokerWithDLQ (0.00s)    
```

where is the `ko` hooked? We can not run `ko` here on OCP.  We have test images already available, e.g. 
https://github.com/openshift/knative-eventing/tree/release-next/openshift/ci-operator/knative-test-images/event-flaker

but not exactly where that (in our case expected) `FAIL` comes from

**Comment by matzew** [comment]
Ah, it's here: https://github.com/knative/eventing/blob/c820f4239730dacf5b2e0e5eed67a496bdc9b424/vendor/knative.dev/reconciler-test/pkg/environment/images.go#L64

can we ... replace / override that ?

**Comment by matzew** [comment]
I wonder if we can easily change this: https://github.com/knative/eventing/blob/c820f4239730dacf5b2e0e5eed67a496bdc9b424/test/rekt/ko_publish_test.go#L33

(or patch)... so it won't run the `ko` parts

**Comment by matzew** [comment]
Not sure I get the "scope" of the `environment.ProduceImages()`

is that all inside the `test/rekt` folder?

**Comment by lionelvillard** [comment]
> Not sure I get the "scope" of the `environment.ProduceImages()`

The scope is the same as the `ko` scope, which is all go packages in the go module.

**Pull request merged**
