### PR TITLE
Some proposal for release scheduling

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

### CODE REVIEW

**Comment by devguyio** [comment]
LGTM, waiting @lberk and @aliok

**Comment by devguyio** [comment]
I had a change of heart which I'd like to share with y'all in our sync call.

**Comment by aliok** [comment]
LGTM

**Comment by lberk** [comment]
/unhold
will add the CI in a different PR

**Pull request merged**
