### PR TITLE
[0.23] Backport of PRs 4815 5321 5444

### PR DESCRIPTION
**Pull request by cardil**
[0.23] Backport of PRs 4815 5321 5444 (from #1309)

* Backport of (knative#4815)
* Backport of (knative#5321)
* Backport of (knative#5444)

4f8c114 is to restore manually modified `vendor` dir, after applying the cherry-pick.

### CODE REVIEW

**Comment by cardil** [comment]
/retest

Infra

**Comment by cardil** [comment]
/retest

Infra once again

**Comment by cardil** [comment]
/retest

Infra yet again

**Review by aliok — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
