### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by pierDipi** [comment]
```
    wait.go:266: Failed while waiting for pod source-bzfhlhpb-rxidllca running: timed out waiting for the condition
        knative.dev/reconciler-test/pkg/k8s.WaitForPodRunningOrFail
        	/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/k8s/wait.go:266
        knative.dev/reconciler-test/pkg/eventshub.Install.func1
        	/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go:81
        knative.dev/reconciler-test/pkg/eventshub.(*EventProber).SenderInstall.func1
        	/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go:139
        knative.dev/reconciler-test/pkg/environment.(*MagicEnvironment).executeStep.func1
        	/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/environment/execution.go:77
        testing.tRunner
        	/usr/local/go/src/testing/testing.go:1259
        runtime.goexit
        	/usr/local/go/src/runtime/asm_amd64.s:1581
    --- FAIL: TestMultiTriggerTopology/Bad_Trigger_does_not_affect_good_Trigger/Requirement/install_source (120.29s)
```
This test is flaky again.

**Comment by pierDipi** [comment]
```
The connection to the server api.ci-ocp-4-8-amd64-aws-us-west-1-xc4gc.hive.aws.ci.openshift.org:6443 was refused - did you specify the right host or port?
14:39:13.331 ERROR:   🚨 Error (code: 1) occurred at ./hack/lib/namespaces.bash:7, with command: oc create namespace "${ns}"
14:39:13.333 ERROR:   Stack trace:
14:39:13.334 ERROR:    1: ./hack/lib/namespaces.bash:19 ensure_namespace(...)
14:39:13.336 ERROR:    2: ./hack/install.sh:18 create_namespaces(...)
```
```
Container test exited with code 1, reason Error
---
Running must-gather...
error running backup collection: errors ocurred while gathering data:
    [skipping gathering secrets/support due to error: secrets "support" not found, skipping gathering EgressFirewall.k8s.ovn.org due to error: the server doesn't have a resource type "EgressFirewall", skipping gathering EgressIP.k8s.ovn.org due to error: the server doesn't have a resource type "EgressIP", skipping gathering endpoints/host-etcd-2 due to error: endpoints "host-etcd-2" not found, skipping gathering namespaces/openshift-manila-csi-driver due to error: namespaces "openshift-manila-csi-driver" not found]Error from server (Forbidden): pods "must-gather-" is forbidden: error looking up service account openshift-must-gather-b56h5/default: serviceaccount "default" not found

```

/test 48-conformance-aws-ocp-48

**Comment by pierDipi** [comment]
```
Unable to connect to the server: dial tcp: lookup api.ci-ocp-4-8-amd64-aws-us-west-1-xc4gc.hive.aws.ci.openshift.org on 172.30.0.10:53: no such host
```

**Comment by pierDipi** [comment]
```
    wait.go:255: {
         "metadata": {
          "name": "source-aeyxxaea-yuiyyotw",
          "namespace": "test-smuesccb",
          "uid": "748be74b-9347-42b6-95bf-540c63128fbd",
          "resourceVersion": "67032",
          "creationTimestamp": "2022-01-14T16:16:35Z",
          "labels": {
           "app": "eventshub-source-aeyxxaea-yuiyyotw"
          },
          "annotations": {
           "k8s.v1.cni.cncf.io/network-status": "[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.128.2.95\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]",
           "k8s.v1.cni.cncf.io/networks-status": "[{\n    \"name\": \"openshift-sdn\",\n    \"interface\": \"eth0\",\n    \"ips\": [\n        \"10.128.2.95\"\n    ],\n    \"default\": true,\n    \"dns\": {}\n}]",
           "openshift.io/scc": "anyuid"
          },
          "managedFields": [
           {
            "manager": "rekt.test",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2022-01-14T16:16:35Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
             "f:metadata": {
              "f:labels": {
               ".": {},
               "f:app": {}
              }
             },
             "f:spec": {
              "f:containers": {
               "k:{\"name\":\"eventshub\"}": {
                ".": {},
                "f:env": {
                 ".": {},
                 "k:{\"name\":\"EVENT_GENERATORS\"}": {
                  ".": {},
                  "f:name": {},
                  "f:value": {}
                 },
                 "k:{\"name\":\"EVENT_LOGS\"}": {
                  ".": {},
                  "f:name": {},
                  "f:value": {}
                 },
                 "k:{\"name\":\"INPUT_YAML\"}": {
                  ".": {},
                  "f:name": {},
                  "f:value": {}
                 },
                 "k:{\"name\":\"K_CONFIG_LOGGING\"}": {
                  ".": {},
                  "f:name": {},
                  "f:value": {}
                 },
                 "k:{\"name\":\"K_CONFIG_TRACING\"}": {
                  ".": {},
                  "f:name": {},
                  "f:value": {}
                 },
                 "k:{\"name\":\"POD_NAME\"}": {
                  ".": {},
                  "f:name": {},
                  "f:valueFrom": {
                   ".": {},
                   "f:fieldRef": {
                    ".": {},
                    "f:apiVersion": {},
                    "f:fieldPath": {}
                   }
                  }
                 },
                 "k:{\"name\":\"SINK\"}": {
                  ".": {},
                  "f:name": {},
                  "f:value": {}
                 },
                 "k:{\"name\":\"SYSTEM_NAMESPACE\"}": {
                  ".": {},
                  "f:name": {},
                  "f:valueFrom": {
                   ".": {},
                   "f:fieldRef": {
                    ".": {},
                    "f:apiVersion": {},
                    "f:fieldPath": {}
                   }
                  }
                 }
                },
                "f:image": {},
                "f:imagePullPolicy": {},
                "f:name": {},
                "f:resources": {},
                "f:terminationMessagePath": {},
                "f:terminationMessagePolicy": {}
               }
              },
              "f:dnsPolicy": {},
              "f:enableServiceLinks": {},
              "f:restartPolicy": {},
              "f:schedulerName": {},
              "f:securityContext": {},
              "f:serviceAccount": {},
              "f:serviceAccountName": {},
              "f:terminationGracePeriodSeconds": {}
             }
            }
           },
           {
            "manager": "multus",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2022-01-14T16:16:37Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
             "f:metadata": {
              "f:annotations": {
               "f:k8s.v1.cni.cncf.io/network-status": {},
               "f:k8s.v1.cni.cncf.io/networks-status": {}
              }
             }
            }
           },
           {
            "manager": "kubelet",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2022-01-14T16:16:38Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
             "f:status": {
              "f:conditions": {
               "k:{\"type\":\"ContainersReady\"}": {
                ".": {},
                "f:lastProbeTime": {},
                "f:lastTransitionTime": {},
                "f:message": {},
                "f:reason": {},
                "f:status": {},
                "f:type": {}
               },
               "k:{\"type\":\"Initialized\"}": {
                ".": {},
                "f:lastProbeTime": {},
                "f:lastTransitionTime": {},
                "f:status": {},
                "f:type": {}
               },
               "k:{\"type\":\"Ready\"}": {
                ".": {},
                "f:lastProbeTime": {},
                "f:lastTransitionTime": {},
                "f:message": {},
                "f:reason": {},
                "f:status": {},
                "f:type": {}
               }
              },
              "f:containerStatuses": {},
              "f:hostIP": {},
              "f:phase": {},
              "f:podIP": {},
              "f:podIPs": {
               ".": {},
               "k:{\"ip\":\"10.128.2.95\"}": {
                ".": {},
                "f:ip": {}
               }
              },
              "f:startTime": {}
             }
            }
           }
          ]
         },
         "spec": {
          "volumes": [
           {
            "name": "kube-api-access-smqr8",
            "projected": {
             "sources": [
              {
               "serviceAccountToken": {
                "expirationSeconds": 3607,
                "path": "token"
               }
              },
              {
               "configMap": {
                "name": "kube-root-ca.crt",
                "items": [
                 {
                  "key": "ca.crt",
                  "path": "ca.crt"
                 }
                ]
               }
              },
              {
               "downwardAPI": {
                "items": [
                 {
                  "path": "namespace",
                  "fieldRef": {
                   "apiVersion": "v1",
                   "fieldPath": "metadata.namespace"
                  }
                 }
                ]
               }
              },
              {
               "configMap": {
                "name": "openshift-service-ca.crt",
                "items": [
                 {
                  "key": "service-ca.crt",
                  "path": "service-ca.crt"
                 }
                ]
               }
              }
             ],
             "defaultMode": 420
            }
           }
          ],
          "containers": [
           {
            "name": "eventshub",
            "image": "registry.ci.openshift.org/openshift/knative-nightly:knative-eventing-test-eventshub",
            "env": [
             {
              "name": "SYSTEM_NAMESPACE",
              "valueFrom": {
               "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.namespace"
               }
              }
             },
             {
              "name": "POD_NAME",
              "valueFrom": {
               "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.name"
               }
              }
             },
             {
              "name": "EVENT_LOGS",
              "value": "recorder,logger"
             },
             {
              "name": "EVENT_GENERATORS",
              "value": "sender"
             },
             {
              "name": "INPUT_YAML",
              "value": "http://lib-lhdmwudv.test-smuesccb.svc.cluster.local/events/three.ce"
             },
             {
              "name": "K_CONFIG_LOGGING",
              "value": "{\"zap-logger-config\":\"{\\n  \\\"level\\\": \\\"info\\\",\\n  \\\"development\\\": false,\\n  \\\"outputPaths\\\": [\\\"stdout\\\"],\\n  \\\"errorOutputPaths\\\": [\\\"stderr\\\"],\\n  \\\"encoding\\\": \\\"json\\\",\\n  \\\"encoderConfig\\\": {\\n    \\\"timeKey\\\": \\\"ts\\\",\\n    \\\"levelKey\\\": \\\"level\\\",\\n    \\\"nameKey\\\": \\\"logger\\\",\\n    \\\"callerKey\\\": \\\"caller\\\",\\n    \\\"messageKey\\\": \\\"msg\\\",\\n    \\\"stacktraceKey\\\": \\\"stacktrace\\\",\\n    \\\"lineEnding\\\": \\\"\\\",\\n    \\\"levelEncoder\\\": \\\"\\\",\\n    \\\"timeEncoder\\\": \\\"iso8601\\\",\\n    \\\"durationEncoder\\\": \\\"\\\",\\n    \\\"callerEncoder\\\": \\\"\\\"\\n  }\\n}\\n\"}"
             },
             {
              "name": "K_CONFIG_TRACING",
              "value": "{\"backend\":\"zipkin\",\"debug\":\"true\",\"sample-rate\":\"1\",\"zipkin-endpoint\":\"http://zipkin.knative-eventing.svc:9411/api/v2/spans\"}"
             },
             {
              "name": "SINK",
              "value": "http://broker-ingress.knative-eventing.svc.cluster.local/test-smuesccb/broker-axqetezu"
             }
            ],
            "resources": {},
            "volumeMounts": [
             {
              "name": "kube-api-access-smqr8",
              "readOnly": true,
              "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
             }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent",
            "securityContext": {
             "capabilities": {
              "drop": [
               "MKNOD"
              ]
             }
            }
           }
          ],
          "restartPolicy": "Never",
          "terminationGracePeriodSeconds": 30,
          "dnsPolicy": "ClusterFirst",
          "serviceAccountName": "test-smuesccb",
          "serviceAccount": "test-smuesccb",
          "nodeName": "ip-10-0-163-116.ec2.internal",
          "securityContext": {
           "seLinuxOptions": {
            "level": "s0:c26,c25"
           }
          },
          "imagePullSecrets": [
           {
            "name": "test-smuesccb-dockercfg-lwhhh"
           }
          ],
          "schedulerName": "default-scheduler",
          "tolerations": [
           {
            "key": "node.kubernetes.io/not-ready",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 300
           },
           {
            "key": "node.kubernetes.io/unreachable",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 300
           }
          ],
          "priority": 0,
          "enableServiceLinks": true,
          "preemptionPolicy": "PreemptLowerPriority"
         },
         "status": {
          "phase": "Failed",
          "conditions": [
           {
            "type": "Initialized",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2022-01-14T16:16:35Z"
           },
           {
            "type": "Ready",
            "status": "False",
            "lastProbeTime": null,
            "lastTransitionTime": "2022-01-14T16:16:35Z",
            "reason": "ContainersNotReady",
            "message": "containers with unready status: [eventshub]"
           },
           {
            "type": "ContainersReady",
            "status": "False",
            "lastProbeTime": null,
            "lastTransitionTime": "2022-01-14T16:16:35Z",
            "reason": "ContainersNotReady",
            "message": "containers with unready status: [eventshub]"
           },
           {
            "type": "PodScheduled",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2022-01-14T16:16:35Z"
           }
          ],
          "hostIP": "10.0.163.116",
          "podIP": "10.128.2.95",
          "podIPs": [
           {
            "ip": "10.128.2.95"
           }
          ],
          "startTime": "2022-01-14T16:16:35Z",
          "containerStatuses": [
           {
            "name": "eventshub",
            "state": {
             "terminated": {
              "exitCode": 1,
              "reason": "Error",
              "startedAt": "2022-01-14T16:16:37Z",
              "finishedAt": "2022-01-14T16:16:37Z",
              "containerID": "cri-o://65713bb154d211212e08433bbeb861527076aabcf11b3734c549ba9fcad76877"
             }
            },
            "lastState": {},
            "ready": false,
            "restartCount": 0,
            "image": "registry.ci.openshift.org/openshift/knative-nightly:knative-eventing-test-eventshub",
            "imageID": "registry.ci.openshift.org/openshift/knative-nightly@sha256:e8294944c51147553e75542d7c7e0f4bf977cbe5b88bfe80d2d84be110cf0ec4",
            "containerID": "cri-o://65713bb154d211212e08433bbeb861527076aabcf11b3734c549ba9fcad76877",
            "started": false
           }
          ],
          "qosClass": "BestEffort"
         }
        }
```

**Comment by pierDipi** [comment]
Fix for collecting logs https://github.com/knative-sandbox/reconciler-test/pull/283/files

**Comment by aliok** [comment]
I am gonna try creating the same pod locally with the same spec.

```
"containerStatuses": [
           {
            "name": "eventshub",
            "state": {
             "terminated": {
              "exitCode": 1,
              "reason": "Error",
              "startedAt": "2022-01-14T16:16:37Z",
              "finishedAt": "2022-01-14T16:16:37Z",
              "containerID": "cri-o://65713bb154d211212e08433bbeb861527076aabcf11b3734c549ba9fcad76877"
             }
            },
            "lastState": {},
            "ready": false,
            "restartCount": 0,
            "image": "registry.ci.openshift.org/openshift/knative-nightly:knative-eventing-test-eventshub",
            "imageID": "registry.ci.openshift.org/openshift/knative-nightly@sha256:e8294944c51147553e75542d7c7e0f4bf977cbe5b88bfe80d2d84be110cf0ec4",
            "containerID": "cri-o://65713bb154d211212e08433bbeb861527076aabcf11b3734c549ba9fcad76877",
            "started": false
           }
          ],
          "qosClass": "BestEffort"
         }
```

**Comment by aliok** [comment]
I've got this:
```
{"level":"fatal","ts":"2022-01-17T07:29:40.382Z","logger":"eventshub","caller":"recorder_vent/constructor.go:59","msg":"Error while trying to retrieve the podpods \"source-aeyxxaea-yuiyyotw\" is forbidden: User \"system:serviceaccount:default:default\" cannot get resource \"pods\" in API group \"\" in the namespace \"default\"","stacktrace":"knative.dev/reconciler-test/pkg/eventshub/recorder_vent.NewEventLog\n\t/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/constructor.go:59\nknative.dev/reconciler-test/pkg/eventshub/recorder_vent.NewFromEnv\n\t/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/constructor.go:53\nmain.main.func1\n\t/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/cmd/eventshub/main.go:35\nknative.dev/reconciler-test/pkg/eventshub.createEventLogs\n\t/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go:74\nknative.dev/reconciler-test/pkg/eventshub.Start\n\t/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go:56\nmain.main\n\t/go/src/knative.dev/eventing/vendor/knative.dev/reconciler-test/cmd/eventshub/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
```

Which could mean nothing because I didn't do the exact same setup with SA and stuff locally. I just created the pod to maybe see what's crashing.

Gonna check if this role requirement is new.

**Pull request closed without merging**
