### PR TITLE
Test script for release-0.3 OpenShift 4

### PR DESCRIPTION
**Pull request by mgencur**
Depends on https://github.com/openshift/knative-eventing/pull/25 which needs to be integrated first. Then we can let CI verify the current PR.

### CODE REVIEW

**Comment by mgencur** [comment]
Both the e2e test and Demo failed. They need to be investigated. Knative itself seems to be installed successfully.

**Comment by bbrowning** [comment]
Knative Serving did not install successfully, actually:
```
====================================
==== INSTALLING KNATIVE SERVING ====
====================================
securitycontextconstraints.security.openshift.io/anyuid added to: ["system:serviceaccount:knative-build:build-controller"]
+ oc adm policy add-scc-to-user anyuid -z controller -n knative-serving
securitycontextconstraints.security.openshift.io/anyuid added to: ["system:serviceaccount:knative-serving:controller"]
+ oc adm policy add-scc-to-user anyuid -z autoscaler -n knative-serving
securitycontextconstraints.security.openshift.io/anyuid added to: ["system:serviceaccount:knative-serving:autoscaler"]
+ oc adm policy add-cluster-role-to-user cluster-admin -z build-controller -n knative-build
Warning: ServiceAccount 'build-controller' not found
clusterrole.rbac.authorization.k8s.io/cluster-admin added: "build-controller"
+ oc adm policy add-cluster-role-to-user cluster-admin -z controller -n knative-serving
Warning: ServiceAccount 'controller' not found
clusterrole.rbac.authorization.k8s.io/cluster-admin added: "controller"
+ curl -L https://github.com/knative/serving/releases/download/v0.3.0/release.yaml
+ sed /nodePort/d
+ oc apply -f -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9    0     9    0     0     30      0 --:--:-- --:--:-- --:--:--    30
100     9    0     9    0     0     30      0 --:--:-- --:--:-- --:--:--    30
error: unable to decode "STDIN": json: cannot unmarshal string into Go value of type unstructured.detector
+ oc -n get cm config-controller -oyaml
+ sed 's/\(^ *registriesSkippingTagResolving.*$\)/\1,image-registry.openshift-image-registry.svc:5000/'
+ oc apply -f -
Error: unknown command "cm" for "oc"

Did you mean this?
	adm
	cp
	ex

Run 'oc --help' for usage.
error: no objects passed to apply
+ echo '>> Patching knative-ingressgateway'
+ oc patch hpa -n istio-system knative-ingressgateway --patch '{"spec": {"maxReplicas": 1}}'
>> Patching knative-ingressgateway
Error from server (NotFound): horizontalpodautoscalers.autoscaling "knative-ingressgateway" not found
```

Something went wrong in the setup script and it ran past the errors instead of existing.

**Comment by bbrowning** [comment]
The URL `https://github.com/knative/serving/releases/download/v0.3.0/release.yaml` is wrong - for 0.3.0 that should be `https://github.com/knative/serving/releases/download/v0.3.0/serving.yaml`

**Comment by mgencur** [comment]
@bbrowning thanks, Ben. Trying with the fixed URL now.

**Comment by bbrowning** [comment]
Hmmm - `e2etestfn3                     5m31s       Warning   FailedScheduling                Pod                       0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.`

**Comment by mgencur** [comment]
YAY! All tests passed, including the Demo. I'm going to add one more commit to clean up some stuff before this can be integrated.

**Comment by mgencur** [comment]
/retest

Hmm, strange. Everything looks ok but the Dumpy service won't return anything.

**Comment by mgencur** [comment]
Cool. This is ready for review.

**Comment by bbrowning** [comment]
Kicking against just to check for stability

/test e2e

**Comment by bbrowning** [comment]
/lgtm

Thanks!

**Pull request merged**
