### PR TITLE
[release-v0.17.2] Backport of upstream PR 4460

### PR DESCRIPTION
**Pull request by cardil**
This PR is meant to be applied after #948 (a revert).

This is a backport of an upstream PR knative#4460, which addresses Upgrade tests wathola-receiver delivery report fetching (knative#3175) in a proper way.

Those changes are required to run Eventing upgrade tests on OpenShift (GA requirement).

### CODE REVIEW

**Comment by cardil** [comment]
/hold

#948 needs to be merged before this. Remove hold badge after merging #948

**Comment by cardil** [comment]
/unhold

This PR should be now ready to review and merge. There are 3 commits:

 * 68924eeff39c9365b0999567250d16b09501b1f1 is backport of knative#4460 without any review requested changes
 * beb301dd79fe50c9f925b2601ca05034f02afbac adds a wathola-fetcher test image
 * ee731f40e38336a60265f9cccf65d6ae412a0411 adds a TIP comment to Makefile on how to override openshift/release repo location

There is also connected openshift/release#13412 in flight

**Comment by devguyio** [comment]
/assign
@lberk @aliok just an FYI I'm on this

**Comment by devguyio** [comment]
/lgtm
I reviewed the code, minor comments I'll leave later to be ironed upstream.

 I'll leave it to @matzew or @lberk to approve in case any CI shenanigans are missing

**Pull request merged**
