### PR TITLE
[release-v0.25] don't generate periodics for nightly and fix pomotion name (#1487)

### PR DESCRIPTION
**Pull request by devguyio**
backport of #1487

### CODE REVIEW

**Comment by devguyio** [comment]
infra failure
/retest

**Comment by matzew** [comment]
/retest

not sure we need to really backport these changes to the "old" :smile: branch.
But
/lgtm

**Comment by devguyio** [comment]
> /retest
> 
> not sure we need to really backport these changes to the "old" smile branch. But /lgtm

Reason for backporting is to avoid ending up in a totally divergent state, which will prevent us from using `/cherry-pick` automation against this branch.

**Pull request merged**
