### PR TITLE
[0.17] Port new recordevents

### PR DESCRIPTION
**Pull request by slinkydeveloper**

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
/hold

I'm testing if this affects eventing-contrib tests too

**Comment by matzew** [comment]
> I'm testing if this affects eventing-contrib tests too

you patching this in the vendor?  or applying the patch upstream, to 0.17 branches ?

**Comment by slinkydeveloper** [comment]
> you patching this in the vendor? 

In vendor

**Comment by matzew** [comment]
@slinkydeveloper if this all goes "well" - let's backport to upstream 0.17 release branch

**Comment by matzew** [comment]
@slinkydeveloper wanna bump, out of curiosity the `parallel` a bit ? to like 6 ?

**Pull request merged**
