### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by devguyio** [comment]
Possibly infra
```

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true
failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
error: build error: error building at STEP "RUN yum install -y kubectl httpd-tools": error while running runtime: exit status 1
```
/retest

**Comment by pierDipi** [comment]
I think this is the fix https://github.com/openshift/release/pull/27443

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
