### PR TITLE
Add a compilation check to the CI run to catch issues in PRs

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title. This compiles the entire repo (including tests we don't run in CI), to make sure there are no compilation errors missed in CI.

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by cardil** [comment]
Why go test instead of go build?

We should add also tags to compile optional code as well.

**Comment by markusthoemmes** [comment]
`go build` doesn't build tests. Ack on the tests, added those.

**Review by cardil — APPROVED** [review]
/lgtm

**Comment by matzew** [comment]
I think it needs https://github.com/openshift/knative-eventing/pull/957 ? :-)

**Comment by markusthoemmes** [comment]
^^ Works as expected :)

**Comment by markusthoemmes** [comment]
Yeah @matzew, did that on purpose to see if it works as I intended it too :joy:

**Comment by markusthoemmes** [comment]
Rebased.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
