### PR TITLE
[release-v0.24] Generate cluster pool stanza for OCP 4.8

### PR DESCRIPTION
**Pull request by mgencur**
Generates CI config using cluster pools that is used in https://github.com/openshift/release/pull/21286

### CODE REVIEW

**Comment by mgencur** [comment]
The reconciler failure is reported as https://issues.redhat.com/browse/SRVKE-918 . It is not related to this PR.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
@mgencur can you port these 0.24 changes also over to the 0.25 branch? 

But I that branch does not yet have CI enabled /cc @lberk for triage

**Comment by mgencur** [comment]
@matzew there's this one which you can merge to main branch: https://github.com/openshift/knative-eventing/pull/1377 , then it should be automatically on 0.25 when we create it.

**Comment by matzew** [comment]
> automatically on 0.25 when we create it

the branch is already created - but not enabled yet.

**Comment by mgencur** [comment]
> the branch is already created - but not enabled yet.
Ok. then I can send it against 0.25 too

**Comment by matzew** [comment]
manually merged this PR, since the bot is out of office

**Pull request merged**
