### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Review by devguyio — APPROVED** [review]

**Comment by aliok** [comment]
/test 47-e2e-aws-ocp-47

Looks like a flake to me

**Comment by pierDipi** [comment]
This is the error:
```
    broker_defaults_webhook_test.go:96: CM updated - new values: |
          clusterDefault:
            apiVersion: v1
            brokerClass: MTChannelBasedBroker
            delivery:
              backoffDelay: PT0.2S
              backoffPolicy: exponential
              retry: 10
            kind: ConfigMap
            name: config-br-default-channel
            namespace: knative-eventing
          namespaceDefaults:
            eventing-e2e2:
              apiVersion: v1
              brokerClass: MTChannelBasedBroker
              delivery:
                backoffDelay: PT0.5S
                backoffPolicy: exponential
                retry: 5
              kind: ConfigMap
              name: config-br-default-channel
              namespace: knative-eventing
        
Failed to get eventing-e2e38/default: brokers.eventing.knative.dev "default" not found
=== CONT  TestBrokerNamespaceDefaulting
    broker_defaults_webhook_test.go:155: 
        	Error Trace:	broker_defaults_webhook_test.go:155
        	            				util.go:51
        	            				wait.go:217
        	            				wait.go:230
        	            				wait.go:223
        	            				wait.go:418
        	            				util.go:50
        	            				broker_defaults_webhook_test.go:118
        	Error:      	Not equal: 
        	            	expected: "PT0.5S"
        	            	actual  : "PT0.2S"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-PT0.5S
        	            	+PT0.2S
        	Test:       	TestBrokerNamespaceDefaulting
    broker_defaults_webhook_test.go:156: 
        	Error Trace:	broker_defaults_webhook_test.go:156
        	            				util.go:51
        	            				wait.go:217
        	            				wait.go:230
        	            				wait.go:223
        	            				wait.go:418
        	            				util.go:50
        	            				broker_defaults_webhook_test.go:118
        	Error:      	Not equal: 
        	            	expected: 5
        	            	actual  : 10
        	Test:       	TestBrokerNamespaceDefaulting
Failed to get eventing-e2e35/default: brokers.eventing.knative.dev "default" not found
=== CONT  TestBrokerNamespaceDefaulting
    broker_defaults_webhook_test.go:171: 
        	Error Trace:	broker_defaults_webhook_test.go:171
        	            				wait.go:217
        	            				wait.go:230
        	            				wait.go:657
        	            				wait.go:591
        	            				wait.go:455
        	            				wait.go:440
        	            				broker_defaults_webhook_test.go:163
        	Error:      	Not equal: 
        	            	expected: "PT0.5S"
        	            	actual  : "PT0.2S"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-PT0.5S
        	            	+PT0.2S
        	Test:       	TestBrokerNamespaceDefaulting
    broker_defaults_webhook_test.go:172: 
        	Error Trace:	broker_defaults_webhook_test.go:172
        	            				wait.go:217
        	            				wait.go:230
        	            				wait.go:657
        	            				wait.go:591
        	            				wait.go:455
        	            				wait.go:440
        	            				broker_defaults_webhook_test.go:163
        	Error:      	Not equal: 
        	            	expected: 5
        	            	actual  : 10
        	Test:       	TestBrokerNamespaceDefaulting
=== CONT  TestBrokerNamespaceDefaulting
```

**Comment by aliok** [comment]
hm,
@pierDipi you've changed some defaults recently, right? but, that was for Kafka stuff... I am confused...

**Comment by pierDipi** [comment]
No, it was for every broker in eventing core.

Due to the defaulting change, this function isn't reliable anymore:
https://github.com/knative/eventing/blob/e05267a8c7cde38049729aef70c5159286f835f5/test/e2e/broker_defaults_webhook_test.go#L185-L187

We need to check for the expected delivery spec parameters.

**Comment by aliok** [comment]
Hm, how did this get merged?

**Pull request merged**
