### PR TITLE
[release-v1.1] Set dead letter sink URI in the `Channel` status (#6256) (#6263)

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry pick of https://github.com/knative/eventing/pull/6263/files

### CODE REVIEW

**Comment by pierDipi** [comment]
/cherry-pick release-v1.0

(the upstream equivalent is still ongoing under testing, so using cherry picker automation for 1.0)

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
@matzew we need this first https://github.com/openshift/knative-eventing/pull/1654

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
same infra
/retest

**Comment by pierDipi** [comment]
same infra
/retest

**Review by pierDipi — COMMENTED** [review]
/lgtm
/approve

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
