### PR TITLE
[release-1.2] Set dead letter sink URI in the `Channel` status (#6262)

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick https://github.com/knative/eventing/pull/6262/files

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by pierDipi** [comment]
until we fix the issue in 1.2

/approve cancel

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
