### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by matzew** [comment]
/retest

all on smokes...

**Comment by pierDipi** [comment]
```

  * could not run steps: step reconciler-aws-ocp-410 failed: failed to wait for the created cluster claim to become ready: timed out waiting for the condition 
INFO[2022-05-24T02:00:04Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:utilizing_cluster_claim:acquiring_cluster_claim' 
```
/retest

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
