### PR TITLE
Dev experience release next

### PR DESCRIPTION
**Pull request by mgencur**
Same as https://github.com/openshift/knative-eventing/pull/646 , just testing it against release-next. When the current PR passes the other PR for master branch can be merged there.

### CODE REVIEW

**Comment by matzew** [comment]
something seems wrong ? :thinking:

**Comment by mgencur** [comment]
Oh. I think still the v1alpha1 vs beta1 channel.

**Comment by matzew** [comment]
@mgencur see? copy/past errors, due to duplicating this file :-)

**Pull request merged**
