### PR TITLE
[v0.25] Make SubscriptionSpec.Delivery mutable

### PR DESCRIPTION
**Pull request by pierDipi**
Cherry-pick of https://github.com/knative/eventing/pull/6139/files

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

/cc @maschmid @matzew

### CODE REVIEW

**Comment by pierDipi** [comment]
```

ERRO[2022-02-08T12:09:52Z] 
  * could not run steps: step knative-eventing-schema failed: could not wait for build knative-eventing-schema to be deleted: timed out waiting for the condition 
  * ```
/test 47-conformance-aws-ocp-47

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
