### PR TITLE
WIP: Test

### PR DESCRIPTION
**Pull request by matzew**
just testing if the rek-test here still works, last PR here (https://github.com/openshift/knative-eventing/pull/1328) it did actually work.

.....

### CODE REVIEW

**Comment by matzew** [comment]
@lberk isnt it interesting the shizzle works here?

**Comment by lberk** [comment]
@matzew I'm not sure I see the upgrade tests running
@cardil do we not run the upgrade tests on midstream branches?

**Comment by matzew** [comment]
@lberk I mean the REKT-TEST 

Diferent note: Not sure why we don't do upgrade tests on midstream, tbh

**Pull request closed without merging**
