### PR TITLE
Fix override from release-next to release-v0.16.0

### PR DESCRIPTION
**Pull request by lberk**

### CODE REVIEW

**Comment by matzew** [comment]
perhaps we do the sed thing here too? Seems like a very reasonable thing to do, and avoids the issue of images not there for test, initally

**Comment by lberk** [comment]
I'm realizing the issue with 'the sed thing' here is that we pass our yaml into the operator catalogsource via `args:` whereas the serving bits have it directly in the catalogsource

**Comment by matzew** [comment]
@lberk we could `sed` on our yamls and rewrite those ? so we can still pass them to the Catalogsource

**Pull request closed without merging**
