### PR TITLE
Do not proxy some headers from reply

### PR DESCRIPTION
**Pull request by aliok**
Related: https://github.com/knative-sandbox/eventing-kafka-broker/issues/2122

Let's try this quickly downstream at SO and then I can create a PR in the upstream (and also other branches) asking for Security WG feedback.

This is very hard to test because when I tell the mock http server to send a specific `Content-Length` with the reply for checking, it responds with `502`

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by matzew** [comment]
> (let's hold these PRs until we're confident in it)

I already tested it - it works

**Pull request merged**
