### PR TITLE
[release-v0.23] Use dependencies instead of IMAGE_FORMAT and switch to cluster pool

### PR DESCRIPTION
**Pull request by devguyio**
- Switch to dependencies instead of IMAGE_FORMAT
- Use cluster pool for 4.8

based on  openshift/knative-eventing#1377

### CODE REVIEW

**Comment by devguyio** [comment]
Might be hive related error, not 100% sure. 

/retest

```
12:22:59.336 DEBUG:   Context: admin, Cluster: ci-ocp-4-8-amd64-aws-us-east-1-5zzl5, Server: https://api.ci-ocp-4-8-amd64-aws-us-east-1-5zzl5.hive.aws.ci.openshift.org:6443
12:22:59.338 DEBUG:   bash -c '! oc login --kubeconfig=puller.kubeconfig --insecure-skip-tls-verify=true --username=puller --password=puller https://api.ci-ocp-4-8-amd64-aws-us-east-1-5zzl5.hive.aws.ci.openshift.org:6443 > /dev/null' : Waiting until non-zero (max 600 sec.)
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
12:47:19.607 ERROR:   Time out of 600 exceeded
12:47:19.609 ERROR:   🚨 Error (code: 71) occurred at ./hack/lib/catalogsource.bash:38, with command: return 71
12:47:19.613 ERROR:   Stack trace:
12:47:19.615 ERROR:    1: ./hack/lib/catalogsource.bash:21 add_user(...)
12:47:19.618 ERROR:    2: ./hack/lib/catalogsource.bash:9 install_catalogsource(...)
12:47:19.620 ERROR:    3: ./hack/install.sh:21 ensure_catalogsource_installed(...)
pod ci-op-lw3rk696/reconciler-aws-ocp-48-test failed after 32m50s (failed containers: test): ContainerFailed one or more containers exited
```

**Comment by devguyio** [comment]
The 0.23 updates jobs introduced in openshift/release#21990 had removed a timeout that was set specifically for `v0.24` on 4.7 which is probably why the jobs are timing out. I'm reintroducing them here openshift/release#22009

**Comment by matzew** [comment]
/hold 
to be safe....

**Pull request merged**
